server {
    listen 8080;

    add_header X-N8N-Origin "ci-lab-node" always;   # header-disclosure test
    add_header Access-Control-Allow-Origin $http_origin always;   # CORS reflect test
    add_header Access-Control-Allow-Credentials "true" always;

    # deliberately leaky path -- for file-exposure detection test
    location = /.env {
        alias /usr/share/nginx/leaky/.env;
    }

    location / {
        proxy_pass http://n8n:5678;
        proxy_set_header Host $host;
    }
}
